// snatch 💎
export const theme = {
  theme_name: 'vkComDark',
  theme_inherits_from: 'vkBaseDark',
  colors_scheme: 'dark',
  size:{
    size_border_radius__regular: '8px',
    size_border_radius_paper__regular: '12px',
    size_check_border_radius__regular: '4px',
    size_button_large_height__regular: '44px',
    size_button_large_height__compact: '36px',
    size_button_medium_height__regular: '36px',
    size_button_medium_height__compact: '32px',
    size_button_small_height__regular: '30px',
    size_button_small_height__compact: '28px',
  },
  palette: {
    color_background_accent: '#71AAEB',
    color_background_accent__hover: '#77ADEC',
    color_background_accent__active: '#7CB1ED',
    color_background_accent_themed: '#E1E3E6',
    color_background_accent_themed__hover: '#D8DBDF',
    color_background_accent_themed__active: '#CFD2D8',
    color_background_accent_tint__hover: '#61A2FF',
    color_background_accent_tint__active: '#67A6FF',
    color_background_accent_alternative: '#71AAEB',
    color_background_accent_alternative__hover: '#77ADEC',
    color_background_accent_alternative__active: '#7CB1ED',
    color_background: '#141414',
    color_background__hover: '#1D1D1D',
    color_background__active: '#272727',
    color_background_content: '#222222',
    color_background_content__hover: '#2B2B2B',
    color_background_content__active: '#343434',
    color_background_secondary: '#333333',
    color_background_secondary__hover: '#3B3B3B',
    color_background_secondary__active: '#434343',
    color_background_secondary_alpha: 'rgba(255, 255, 255, 0.10)',
    color_background_secondary_alpha__hover: 'rgba(255, 255, 255, 0.12)',
    color_background_secondary_alpha__active: 'rgba(255, 255, 255, 0.14)',
    color_background_tertiary: '#292929',
    color_background_tertiary__hover: '#323232',
    color_background_tertiary__active: '#3A3A3A',
    color_background_tertiary_alpha: 'rgba(255, 255, 255, 0.03)',
    color_background_tertiary_alpha__hover: 'rgba(255, 255, 255, 0.07)',
    color_background_tertiary_alpha__active: 'rgba(255, 255, 255, 0.11)',
    color_background_contrast__hover: '#EBEDF0',
    color_background_contrast__active: '#D7D8DB',
    color_background_contrast_inverse__hover: '#3B3B3B',
    color_background_contrast_inverse__active: '#434343',
    color_background_modal: '#333333',
    color_background_modal__hover: '#3B3B3B',
    color_background_modal__active: '#434343',
    color_background_modal_inverse: '#FFFFFF',
    color_background_modal_inverse__hover: '#EBEDF0',
    color_background_modal_inverse__active: '#D7D8DB',
    color_background_warning: '#857250',
    color_background_warning__hover: '#8A7857',
    color_background_warning__active: '#8F7D5E',
    color_background_positive__hover: '#52B652',
    color_background_positive__active: '#59B959',
    color_background_negative: '#FF5C5C',
    color_background_negative__hover: '#FF6363',
    color_background_negative__active: '#FF6969',
    color_background_negative_tint: '#522E2E',
    color_background_negative_tint__hover: '#593636',
    color_background_negative_tint__active: '#603F3F',
    color_background_positive_tint__hover: '#E9F9E9',
    color_background_positive_tint__active: '#EAF9EA',
    color_field_background: '#292929',
    color_field_background__hover: '#323232',
    color_field_background__active: '#3A3A3A',
    color_header_background: '#222222',
    color_header_background__hover: '#2B2B2B',
    color_header_background__active: '#343434',
    color_text_accent: '#71AAEB',
    color_text_accent__hover: '#77ADEC',
    color_text_accent__active: '#7CB1ED',
    color_text_accent_themed: '#E1E3E6',
    color_text_accent_themed__hover: '#E2E4E7',
    color_text_accent_themed__active: '#E3E5E8',
    color_text_primary: '#E1E3E6',
    color_text_primary__hover: '#E2E4E7',
    color_text_primary__active: '#E3E5E8',
    color_text_primary_invariably__hover: '#3B3B3B',
    color_text_primary_invariably__active: '#434343',
    color_text_secondary: '#B2B2B2',
    color_text_secondary__hover: '#B5B5B5',
    color_text_secondary__active: '#B8B8B8',
    color_text_subhead: '#939393',
    color_text_subhead__hover: '#979797',
    color_text_subhead__active: '#9C9C9C',
    color_text_tertiary: '#656565',
    color_text_tertiary__hover: '#6B6B6B',
    color_text_tertiary__active: '#717171',
    color_text_contrast__hover: '#EBEDF0',
    color_text_contrast__active: '#D7D8DB',
    color_text_contrast_themed: '#222222',
    color_text_contrast_themed__hover: '#2B2B2B',
    color_text_contrast_themed__active: '#343434',
    color_text_positive__hover: '#52B652',
    color_text_positive__active: '#59B959',
    color_text_negative: '#FF5C5C',
    color_text_negative__hover: '#FF6363',
    color_text_negative__active: '#FF6969',
    color_text_link: '#71AAEB',
    color_text_link__hover: '#77ADEC',
    color_text_link__active: '#7CB1ED',
    color_text_link_themed: '#939393',
    color_text_link_themed__hover: '#979797',
    color_text_link_themed__active: '#9C9C9C',
    color_text_link_visited__hover: '#508BCE',
    color_text_link_visited__active: '#5890D0',
    color_text_muted: '#CCCCCC',
    color_text_muted__hover: '#CECECE',
    color_text_muted__active: '#D0D0D0',
    color_link_contrast: '#CCCCCC',
    color_link_contrast__hover: '#CECECE',
    color_link_contrast__active: '#D0D0D0',
    color_icon_accent: '#71AAEB',
    color_icon_accent__hover: '#77ADEC',
    color_icon_accent__active: '#7CB1ED',
    color_icon_accent_themed: '#E1E3E6',
    color_icon_accent_themed__hover: '#E2E4E7',
    color_icon_accent_themed__active: '#E3E5E8',
    color_icon_primary: '#E1E3E6',
    color_icon_primary__hover: '#E2E4E7',
    color_icon_primary__active: '#E3E5E8',
    color_icon_primary_invariably__hover: '#3B3B3B',
    color_icon_primary_invariably__active: '#434343',
    color_icon_medium: '#939393',
    color_icon_medium__hover: '#979797',
    color_icon_medium__active: '#9C9C9C',
    color_icon_medium_alpha: 'rgba(255, 255, 255, 0.48)',
    color_icon_medium_alpha__hover: 'rgba(255, 255, 255, 0.52)',
    color_icon_medium_alpha__active: 'rgba(255, 255, 255, 0.56)',
    color_icon_secondary: '#828282',
    color_icon_secondary__hover: '#878787',
    color_icon_secondary__active: '#8C8C8C',
    color_icon_secondary_alpha: 'rgba(255, 255, 255, 0.40)',
    color_icon_secondary_alpha__hover: 'rgba(255, 255, 255, 0.44)',
    color_icon_secondary_alpha__active: 'rgba(255, 255, 255, 0.48)',
    color_icon_tertiary: '#656565',
    color_icon_tertiary__hover: '#6B6B6B',
    color_icon_tertiary__active: '#717171',
    color_icon_tertiary_alpha: 'rgba(255, 255, 255, 0.24)',
    color_icon_tertiary_alpha__hover: 'rgba(255, 255, 255, 0.28)',
    color_icon_tertiary_alpha__active: 'rgba(255, 255, 255, 0.32)',
    color_icon_contrast: '#E1E3E6',
    color_icon_contrast__hover: '#E2E4E7',
    color_icon_contrast__active: '#E3E5E8',
    color_icon_contrast_themed: '#222222',
    color_icon_contrast_themed__hover: '#2B2B2B',
    color_icon_contrast_themed__active: '#343434',
    color_icon_contrast_secondary__hover: '#F3F3F5',
    color_icon_contrast_secondary__active: '#F3F4F6',
    color_icon_positive__hover: '#52B652',
    color_icon_positive__active: '#59B959',
    color_icon_negative: '#FF5C5C',
    color_icon_negative__hover: '#FF6363',
    color_icon_negative__active: '#FF6969',
    color_stroke_accent: '#71AAEB',
    color_stroke_accent__hover: '#77ADEC',
    color_stroke_accent__active: '#7CB1ED',
    color_stroke_accent_themed: '#E1E3E6',
    color_stroke_accent_themed__hover: '#E2E4E7',
    color_stroke_accent_themed__active: '#E3E5E8',
    color_separator_primary: '#363738',
    color_separator_primary__hover: '#3E3F40',
    color_separator_primary__active: '#464748',
    color_separator_primary2x: '#444546',
    color_separator_primary2x__hover: '#4B4C4D',
    color_separator_primary2x__active: '#535455',
    color_separator_primary3x: '#505253',
    color_separator_primary3x__hover: '#57595A',
    color_separator_primary3x__active: '#5E6061',
    color_separator_primary_alpha: 'rgba(255, 255, 255, 0.12)',
    color_separator_primary_alpha__hover: 'rgba(255, 255, 255, 0.16)',
    color_separator_primary_alpha__active: 'rgba(255, 255, 255, 0.2)',
    color_separator_secondary: '#292929',
    color_separator_secondary__hover: '#323232',
    color_separator_secondary__active: '#3A3A3A',
    color_stroke_positive__hover: '#52B652',
    color_stroke_positive__active: '#59B959',
    color_stroke_negative: '#FF5C5C',
    color_stroke_negative__hover: '#FF6363',
    color_stroke_negative__active: '#FF6969',
    color_stroke_contrast__hover: '#EBEDF0',
    color_stroke_contrast__active: '#D7D8DB',
    color_image_border_alpha: 'rgba(255, 255, 255, 0.08)',
    color_image_border_alpha__hover: 'rgba(255, 255, 255, 0.12)',
    color_image_border_alpha__active: 'rgba(255, 255, 255, 0.16)',
    color_field_border_alpha: 'rgba(255, 255, 255, 0.12)',
    color_field_border_alpha__hover: 'rgba(255, 255, 255, 0.16)',
    color_field_border_alpha__active: 'rgba(255, 255, 255, 0.2)',
    color_accent_blue: '#397DCC',
    color_accent_blue__hover: '#4182CE',
    color_accent_blue__active: '#4987D0',
    color_accent_gray__hover: '#B1BAC4',
    color_accent_gray__active: '#B4BDC7',
    color_accent_red__hover: '#FF3B4E',
    color_accent_red__active: '#FF4356',
    color_accent_green: '#4BB34B',
    color_accent_green__hover: '#52B652',
    color_accent_green__active: '#59B959',
    color_accent_orange__hover: '#FFA40A',
    color_accent_orange__active: '#FFA814',
    color_accent_purple: '#937FF5',
    color_accent_purple__hover: '#9784F5',
    color_accent_purple__active: '#9C89F6',
    color_accent_violet: '#A393F5',
    color_accent_violet__hover: '#A797F5',
    color_accent_violet__active: '#AA9CF6',
    color_accent_secondary__hover: '#478FE1',
    color_accent_secondary__active: '#4E93E2',
    color_image_placeholder: '#2A2B2C',
    color_image_placeholder__hover: '#333334',
    color_image_placeholder__active: '#3B3C3D',
    color_image_placeholder_alpha: 'rgba(241, 247, 255, 0.08)',
    color_image_placeholder_alpha__hover: 'rgba(241, 247, 255, 0.12)',
    color_image_placeholder_alpha__active: 'rgba(241, 247, 255, 0.16)',
    color_skeleton_from: '#292929',
    color_skeleton_from__hover: '#323232',
    color_skeleton_from__active: '#3A3A3A',
    color_skeleton_to: '#333333',
    color_skeleton_to__hover: '#3B3B3B',
    color_skeleton_to__active: '#434343',
    color_write_bar_icon: '#E1E3E6',
    color_write_bar_icon__hover: '#E2E4E7',
    color_write_bar_icon__active: '#E3E5E8',
    color_write_bar_input_background: '#424242',
    color_write_bar_input_background__hover: '#4A4A4A',
    color_write_bar_input_background__active: '#515151',
    color_write_bar_input_border_alpha: 'rgba(255, 255, 255, 0.8)',
    color_write_bar_input_border_alpha__hover: 'rgba(255, 255, 255, 0.84)',
    color_write_bar_input_border_alpha__active: 'rgba(255, 255, 255, 0.88)',
    color_action_sheet_text: '#529EF4',
    color_action_sheet_text__hover: '#59A2F4',
    color_action_sheet_text__active: '#60A6F5',
    color_track_background: '#828282',
    color_track_background__hover: '#878787',
    color_track_background__active: '#8C8C8C',
    color_track_buffer: '#FFFFFF',
    color_track_buffer__hover: '#EBEDF0',
    color_track_buffer__active: '#D7D8DB',
    color_search_field_background: '#424242',
    color_search_field_background__hover: '#4A4A4A',
    color_search_field_background__active: '#515151',
    color_panel_header_icon: '#71AAEB',
    color_panel_header_icon__hover: '#77ADEC',
    color_panel_header_icon__active: '#7CB1ED',
    color_segmented_control: '#626364',
    color_segmented_control__hover: '#68696A',
    color_segmented_control__active: '#6F6F70',
    color_transparent__hover: 'rgba(255, 255, 255, 0.04)',
    color_transparent__active: 'rgba(255, 255, 255, 0.08)',
  },
}
